version: "3.5"
name: "pingora-load-balancer"

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER1_ADDR: "1.1.1.1:443"
      SERVER2_ADDR: "1.0.1.0:443"
      LISTEN_PORT: "9999"
    expose:
      - "9999"